/**
 * YanCe Policy Agent - Chrome Extension
 * popup.js
 *
 * Handles page content extraction, policy analysis simulation,
 * and rendering of structured results.
 * Brand: yance.ai
 */

// ============================================
// DOM Elements
// ============================================
const btnAnalyze = document.getElementById('btn-analyze');
const btnServiceNote = document.getElementById('btn-service-note');
const btnCopyParkOps = document.getElementById('btn-copy-parkops');
const btnOpenDashboard = document.getElementById('btn-open-dashboard');
const loadingEl = document.getElementById('loading');
const resultsEl = document.getElementById('results');

// Store the current analysis for ParkOps copy
let currentAnalysis = null;

// ============================================
// Event Listeners
// ============================================
btnAnalyze.addEventListener('click', handleAnalyze);
btnServiceNote.addEventListener('click', handleServiceNote);
btnCopyParkOps.addEventListener('click', handleCopyParkOps);
btnOpenDashboard.addEventListener('click', handleOpenDashboard);

// ============================================
// Main Handlers
// ============================================

/**
 * Analyze the current page for policy content.
 */
async function handleAnalyze() {
  disableButtons(true);
  showLoading(true);
  hideResults();

  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

    if (!tab || !tab.id) {
      throw new Error('无法获取当前标签页');
    }

    const pageText = await extractPageText(tab.id);
    const analysis = analyzePolicyContent(pageText, tab.url, tab.title);

    currentAnalysis = analysis;
    renderAnalysisResults(analysis);
    showResults();
  } catch (error) {
    console.error('Analysis error:', error);
    const mockAnalysis = getMockAnalysis();
    currentAnalysis = mockAnalysis;
    renderAnalysisResults(mockAnalysis);
    showResults();
  } finally {
    showLoading(false);
    disableButtons(false);
  }
}

/**
 * Generate a park service note based on current page.
 */
async function handleServiceNote() {
  disableButtons(true);
  showLoading(true);
  hideResults();

  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    const pageText = tab ? await extractPageText(tab.id) : '';
    const analysis = analyzePolicyContent(pageText, tab ? tab.url : '', tab ? tab.title : '');

    const serviceNote = generateServiceNote(analysis);
    currentAnalysis = serviceNote;
    renderAnalysisResults(serviceNote);
    showResults();
  } catch (error) {
    console.error('Service note error:', error);
    const mockAnalysis = getMockAnalysis();
    currentAnalysis = mockAnalysis;
    renderAnalysisResults(mockAnalysis);
    showResults();
  } finally {
    showLoading(false);
    disableButtons(false);
  }
}

/**
 * Copy structured analysis as a ParkOps service ticket.
 */
function handleCopyParkOps() {
  if (!currentAnalysis) {
    return;
  }

  const now = new Date();
  const ticketId = `SVC-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;

  const ticket = [
    `═══════════════════════════════════════`,
    `  ParkOps 服务工单  |  yance.ai`,
    `═══════════════════════════════════════`,
    ``,
    `工单编号：${ticketId}`,
    `创建时间：${now.toLocaleString('zh-CN')}`,
    `来源工具：YanCe Policy Agent Chrome Extension`,
    ``,
    `── 政策信息 ──`,
    `政策名称：${currentAnalysis.policyName || '待确认'}`,
    `发文机关：${currentAnalysis.issuingAuthority || '待确认'}`,
    `适用区域：${currentAnalysis.region || '待确认'}`,
    `目标产业：${(currentAnalysis.targetIndustries || []).join('、') || '待确认'}`,
    `补贴金额：${currentAnalysis.subsidyAmount || '待确认'}`,
    `申报截止：${currentAnalysis.deadline || '待确认'}`,
    ``,
    `── 适用企业类型 ──`,
    `${(currentAnalysis.enterpriseTypes || []).join('、')}`,
    ``,
    `── 申报条件 ──`,
    ...(currentAnalysis.conditions || []).map((c, i) => `  ${i + 1}. ${c}`),
    ``,
    `── 所需材料 ──`,
    ...(currentAnalysis.materials || []).map((m, i) => `  ${i + 1}. ${m}`),
    ``,
    `── 服务建议 ──`,
    ...(currentAnalysis.serviceSuggestions || []).map(s => `  [${s.title}] ${s.desc}`),
    ``,
    `── 下一步行动 ──`,
    ...(currentAnalysis.nextSteps || []).map((s, i) => `  ${i + 1}. ${s}`),
    ``,
    `── 风险提示 ──`,
    ...(currentAnalysis.riskTips || []).map(t => `  ! ${t}`),
    ``,
    `═══════════════════════════════════════`,
    `  Generated by yance.ai | YanCe Policy Agent`,
    `═══════════════════════════════════════`,
  ].join('\n');

  navigator.clipboard.writeText(ticket).then(() => {
    btnCopyParkOps.textContent = '已复制到剪贴板';
    btnCopyParkOps.disabled = true;
    setTimeout(() => {
      btnCopyParkOps.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg> 复制到 ParkOps`;
      btnCopyParkOps.disabled = false;
    }, 2000);
  }).catch(() => {
    alert('复制失败，请手动复制');
  });
}

/**
 * Open the yance.ai dashboard in a new tab.
 */
function handleOpenDashboard() {
  chrome.tabs.create({ url: 'https://yance.ai' });
}

// ============================================
// Page Content Extraction
// ============================================

/**
 * Extract text content from the current page via scripting.
 * @param {number} tabId
 * @returns {Promise<string>}
 */
async function extractPageText(tabId) {
  const results = await chrome.scripting.executeScript({
    target: { tabId: tabId },
    func: () => {
      const clone = document.body.cloneNode(true);
      const scripts = clone.querySelectorAll('script, style, noscript, iframe');
      scripts.forEach((el) => el.remove());
      const text = clone.innerText || clone.textContent || '';
      return text.substring(0, 15000);
    },
  });

  return results && results[0] ? results[0].result : '';
}

// ============================================
// Policy Analysis (Heuristic + Structured)
// ============================================

/**
 * Detect if the current page is likely a government policy page.
 * @param {string} text
 * @param {string} url
 * @param {string} title
 * @returns {boolean}
 */
function isGovernmentPolicyPage(text, url, title) {
  const govUrlPatterns = /gov\.cn|\.gov\.|\.edu\.cn|gov\.org|zhengce|zhengfu|weiyuanhui/;
  const policyKeywords = [
    '政策', '补贴', '扶持', '奖励', '资助', '申报', '通知',
    '意见', '办法', '规定', '高新技术', '专精特新', '科技型中小',
    '产业园', '开发区', '高新区', '经开区', '示范区',
    '关于', '印发', '实施', '若干措施', '若干政策',
  ];

  const urlMatch = govUrlPatterns.test(url);
  const keywordCount = policyKeywords.filter((kw) => text.includes(kw)).length;

  return urlMatch || keywordCount >= 3;
}

/**
 * Analyze extracted page text for policy-like content.
 * @param {string} text
 * @param {string} url
 * @param {string} title
 * @returns {object} Structured analysis
 */
function analyzePolicyContent(text, url, title) {
  if (!text || text.length < 50) {
    return getMockAnalysis();
  }

  const isPolicyPage = isGovernmentPolicyPage(text, url, title);

  if (isPolicyPage && text.length > 100) {
    return extractFromRealContent(text, url, title);
  }

  return getMockAnalysis();
}

/**
 * Extract structured policy data from real page content.
 */
function extractFromRealContent(text, url, title) {
  // Detect region
  const regionPatterns = {
    '上海市浦东新区': /上海|沪|浦东新区|张江|临港|漕河泾/,
    '上海市徐汇区': /徐汇/,
    '上海市杨浦区': /杨浦/,
    '北京市中关村': /北京|京|中关村|亦庄|经开区/,
    '深圳市南山区': /深圳|粤|南山|前海|福田/,
    '杭州市余杭区': /杭州|浙|余杭|滨江|未来科技城/,
    '苏州市工业园区': /苏州|苏|工业园区|昆山/,
    '成都市天府新区': /成都|川|天府新区/,
  };

  let detectedRegion = '待确认';
  for (const [region, pattern] of Object.entries(regionPatterns)) {
    if (pattern.test(text) || pattern.test(url)) {
      detectedRegion = region;
      break;
    }
  }

  // Detect issuing authority
  const authorityPatterns = [
    /([\u4e00-\u9fa5]+(?:人民政府|管委会|科技局|发改委|经信委|工信局|科委))/,
    /([\u4e00-\u9fa5]+(?:办公室|财政厅|人社厅|商务厅))/,
  ];
  let issuingAuthority = '待确认';
  for (const pattern of authorityPatterns) {
    const match = text.match(pattern);
    if (match) {
      issuingAuthority = match[1];
      break;
    }
  }

  // Detect policy name from title or first heading
  let policyName = title || '待确认';
  const titlePatterns = [
    /关于[\u4e00-\u9fa5]+(?:的通知|的意见|的办法|的方案|的措施)/,
    /[\u4e00-\u9fa5]+(?:扶持政策|支持政策|发展政策|专项资金)/,
  ];
  for (const pattern of titlePatterns) {
    const match = text.match(pattern);
    if (match) {
      policyName = match[0];
      break;
    }
  }

  // Detect target industries
  const targetIndustries = [];
  const industryMap = {
    '人工智能': /人工智能|AI|大模型|机器学习|深度学习/,
    '生物医药': /生物医药|医药|生物技术|创新药|医疗器械/,
    '集成电路': /集成电路|芯片|半导体|微电子/,
    '新材料': /新材料|先进材料|功能材料/,
    '新能源': /新能源|清洁能源|光伏|储能|风电/,
    '智能制造': /智能制造|机器人|自动化|工业互联网/,
    '软件与信息服务': /软件|信息服务|数字|数据|云计算/,
  };
  for (const [industry, pattern] of Object.entries(industryMap)) {
    if (pattern.test(text)) {
      targetIndustries.push(industry);
    }
  }
  if (targetIndustries.length === 0) targetIndustries.push('科技型企业');

  // Detect enterprise types
  const enterpriseTypes = [];
  if (/高新技术|高企/.test(text)) enterpriseTypes.push('高新技术企业');
  if (/专精特新/.test(text)) enterpriseTypes.push('专精特新企业');
  if (/科技型中小/.test(text)) enterpriseTypes.push('科技型中小企业');
  if (/小微/.test(text)) enterpriseTypes.push('小微企业');
  if (/独角兽/.test(text)) enterpriseTypes.push('独角兽企业');
  if (/瞪羚/.test(text)) enterpriseTypes.push('瞪羚企业');
  if (enterpriseTypes.length === 0) enterpriseTypes.push('科技型企业', '中小企业');

  // Detect subsidy amount
  let subsidyAmount = '详见政策原文';
  const subsidyPatterns = [
    /(?:最高|不超过)\s*([\d,]+)\s*万/,
    /补贴\s*([\d,]+)\s*万/,
    /奖励\s*([\d,]+)\s*万/,
    /资助\s*([\d,]+)\s*万/,
  ];
  for (const pattern of subsidyPatterns) {
    const match = text.match(pattern);
    if (match) {
      subsidyAmount = `最高 ${match[1]} 万元`;
      break;
    }
  }

  // Detect deadline
  let deadline = '详见政策原文';
  const deadlinePatterns = [
    /(?:截止|截至|申报期限)[：:]*\s*(\d{4}年\d{1,2}月\d{1,2}日)/,
    /(\d{4}年\d{1,2}月\d{1,2}日)(?:前|之前)/,
    /(\d{4}年\d{1,2}月)/,
  ];
  for (const pattern of deadlinePatterns) {
    const match = text.match(pattern);
    if (match) {
      deadline = match[1];
      break;
    }
  }

  // Extract summary (first meaningful paragraphs)
  const paragraphs = text.split(/\n+/).filter((p) => p.trim().length > 20);
  const summary = paragraphs.slice(0, 3).join('\n').substring(0, 500) || text.substring(0, 500);

  return {
    policyName: policyName,
    issuingAuthority: issuingAuthority,
    summary: summary,
    region: detectedRegion,
    targetIndustries: targetIndustries,
    subsidyAmount: subsidyAmount,
    deadline: deadline,
    enterpriseTypes: enterpriseTypes,
    conditions: [
      '在该区域注册并实际经营的独立法人企业',
      '符合国家及地方产业发展方向',
      '企业经营状况良好，无严重违法违规记录',
      '具备相关领域的核心技术或业务能力',
      '按规定提交完整的申报材料',
    ],
    materials: [
      '企业营业执照副本（复印件加盖公章）',
      '企业近年度审计报告或财务报表',
      '相关知识产权证明材料',
      '项目申报书或申请表',
      '企业社保缴纳证明',
      '其他相关佐证材料',
    ],
    riskTips: [
      '请注意申报截止时间，提前准备材料',
      '确保所有材料真实有效，虚假信息将被取消资格',
      '部分政策存在名额限制，建议尽早申报',
      '关注政策是否有配套的地方实施细则',
    ],
    serviceSuggestions: [
      {
        title: '主动通知相关企业',
        desc: '筛选园区内符合条件的企业，主动推送政策信息',
      },
      {
        title: '组织政策解读会',
        desc: '邀请政策制定部门或专业机构进行解读，帮助企业理解政策要点',
      },
      {
        title: '提供申报辅导',
        desc: '协助企业准备申报材料，提高申报成功率',
      },
      {
        title: '建立跟踪机制',
        desc: '跟踪企业申报进度，及时反馈并协助解决问题',
      },
    ],
    nextSteps: [
      '将政策要点整理归档至园区政策库',
      '筛选符合条件的园区企业名单',
      '制作政策摘要推送给目标企业',
      '安排专人跟进企业申报进度',
      '定期汇总政策落地情况并上报',
    ],
  };
}

/**
 * Return a comprehensive mock analysis for demo purposes.
 */
function getMockAnalysis() {
  return {
    policyName: '关于支持园区科技创新企业高质量发展的若干措施',
    issuingAuthority: '上海市浦东新区科技和经济委员会',
    summary:
      '该政策旨在支持园区内科技创新企业发展，围绕企业研发投入、知识产权、人才引进、平台建设等方面提供多维度支持。政策涵盖研发费用补贴、场地租金减免、人才安居保障、公共技术服务平台使用补贴等多项具体措施，重点扶持人工智能、生物医药、集成电路、新材料等战略性新兴产业领域的企业。',
    region: '上海市浦东新区',
    targetIndustries: ['人工智能', '生物医药', '集成电路', '新材料'],
    subsidyAmount: '最高 200 万元（综合补贴总额）',
    deadline: '2025年6月30日',
    enterpriseTypes: [
      '高新技术企业',
      '专精特新企业',
      '科技型中小企业',
      '独角兽企业',
      '瞪羚企业',
    ],
    conditions: [
      '在浦东新区注册并实际经营的独立法人企业',
      '属于人工智能、生物医药、集成电路、新材料等重点产业领域',
      '上年度研发投入占营收比例不低于3%',
      '拥有自主知识产权（发明专利、软著等）',
      '企业经营状况良好，近两年无重大违法违规记录',
      '员工社保缴纳人数不低于上年度的80%',
    ],
    materials: [
      '企业营业执照副本（复印件加盖公章）',
      '上年度审计报告（含研发费用专项审计）',
      '知识产权证书及清单（专利、软著、商标等）',
      '高新技术企业认定证书（如适用）',
      '项目申报书（含项目技术方案及预期效益）',
      '企业近12个月社保缴纳证明',
      '企业纳税证明',
      '场地租赁合同或产权证明',
    ],
    riskTips: [
      '申报窗口期通常较短（约2-4周），请提前备齐所有材料',
      '研发费用归集须符合财务规范，建议提前与审计机构沟通',
      '知识产权须为企业自有，受让获得的需注意时间节点',
      '部分补贴项目采取竞争性评审，不保证100%获批',
      '政策有效期内企业须按要求报送年度经营数据',
    ],
    serviceSuggestions: [
      {
        title: '精准匹配推送',
        desc: '根据园区企业画像，筛选出符合申报条件的企业名单，定向推送政策信息。重点关注研发投入占比高、知识产权储备丰富的企业。',
      },
      {
        title: '组织政策宣讲会',
        desc: '邀请区科委或政策制定部门来园区进行面对面解读，帮助企业准确理解政策要点和申报流程。',
      },
      {
        title: '一对一申报辅导',
        desc: '针对重点企业提供一对一辅导服务，协助准备申报书、整理佐证材料、优化项目描述。',
      },
      {
        title: '搭建材料共享平台',
        desc: '建立园区企业公共材料库，如通用审计报告模板、知识产权清单格式等，降低企业准备成本。',
      },
      {
        title: '跟踪反馈闭环',
        desc: '建立政策申报跟踪台账，定期了解企业申报进度，协助解决申报过程中遇到的问题。',
      },
    ],
    nextSteps: [
      '将本政策录入园区政策库，标记重点标签',
      '在3个工作日内完成园区企业初筛，确定目标推送名单',
      '策划并组织一次政策解读宣讲会（建议在政策发布后2周内）',
      '为重点企业安排一对一辅导时间表',
      '建立申报进度跟踪表，每周更新',
    ],
  };
}

// ============================================
// Service Note Generator
// ============================================

/**
 * Generate a concise service note from analysis.
 */
function generateServiceNote(analysis) {
  const noteSuggestions = analysis.serviceSuggestions.map((s) => ({
    title: s.title,
    desc: `[服务备注] ${s.desc}`,
  }));

  return {
    ...analysis,
    summary: `[园区服务备注]\n${analysis.summary}`,
    serviceSuggestions: noteSuggestions,
  };
}

// ============================================
// Rendering
// ============================================

/**
 * Render analysis results into the DOM.
 * @param {object} analysis
 */
function renderAnalysisResults(analysis) {
  // Policy Name
  const policyNameEl = document.getElementById('policy-name');
  if (policyNameEl) {
    policyNameEl.textContent = analysis.policyName || '待确认';
  }

  // Issuing Authority
  const authEl = document.getElementById('issuing-authority');
  if (authEl) {
    authEl.textContent = analysis.issuingAuthority || '待确认';
  }

  // Summary
  document.getElementById('policy-summary').textContent = analysis.summary;

  // Region
  document.getElementById('applicable-region').textContent = analysis.region;

  // Target Industries (as tags)
  const industryContainer = document.getElementById('target-industry');
  if (industryContainer) {
    industryContainer.innerHTML = '';
    (analysis.targetIndustries || []).forEach((ind) => {
      const tag = document.createElement('span');
      tag.className = 'tag tag-coral';
      tag.textContent = ind;
      industryContainer.appendChild(tag);
    });
  }

  // Subsidy Amount
  const subsidyEl = document.getElementById('subsidy-amount');
  if (subsidyEl) {
    subsidyEl.textContent = analysis.subsidyAmount || '详见政策原文';
  }

  // Deadline
  const deadlineEl = document.getElementById('application-deadline');
  if (deadlineEl) {
    deadlineEl.textContent = analysis.deadline || '详见政策原文';
  }

  // Enterprise Types (as tags)
  const typesContainer = document.getElementById('enterprise-types');
  typesContainer.innerHTML = '';
  analysis.enterpriseTypes.forEach((type) => {
    const tag = document.createElement('span');
    tag.className = 'tag';
    tag.textContent = type;
    typesContainer.appendChild(tag);
  });

  // Conditions
  const conditionsList = document.getElementById('application-conditions');
  conditionsList.innerHTML = '';
  analysis.conditions.forEach((cond) => {
    const li = document.createElement('li');
    li.textContent = cond;
    conditionsList.appendChild(li);
  });

  // Materials
  const materialsList = document.getElementById('material-list');
  materialsList.innerHTML = '';
  analysis.materials.forEach((mat) => {
    const li = document.createElement('li');
    li.textContent = mat;
    materialsList.appendChild(li);
  });

  // Risk Tips
  const riskList = document.getElementById('risk-tips');
  riskList.innerHTML = '';
  analysis.riskTips.forEach((tip) => {
    const li = document.createElement('li');
    li.textContent = tip;
    riskList.appendChild(li);
  });

  // Service Suggestions
  const suggestionsContainer = document.getElementById('service-suggestions');
  suggestionsContainer.innerHTML = '';
  analysis.serviceSuggestions.forEach((suggestion) => {
    const div = document.createElement('div');
    div.style.marginBottom = '8px';
    div.innerHTML = `
      <strong style="color: #7dd3fc; font-size: 12px;">${suggestion.title}</strong>
      <p style="margin-top: 2px; font-size: 12px; color: #cbd5e1;">${suggestion.desc}</p>
    `;
    suggestionsContainer.appendChild(div);
  });

  // Next Steps
  const stepsList = document.getElementById('next-steps');
  stepsList.innerHTML = '';
  analysis.nextSteps.forEach((step) => {
    const li = document.createElement('li');
    li.textContent = step;
    stepsList.appendChild(li);
  });
}

// ============================================
// UI Helpers
// ============================================

function showLoading(show) {
  loadingEl.classList.toggle('hidden', !show);
}

function showResults() {
  resultsEl.classList.remove('hidden');
}

function hideResults() {
  resultsEl.classList.add('hidden');
}

function disableButtons(disabled) {
  btnAnalyze.disabled = disabled;
  btnServiceNote.disabled = disabled;
}
